### ISSUE TITLE
app has benn blocked.

### ISSUE THREAD

**Issue by kexul** [m13253/BiliDan#50] opened 2016-03-10 11:12 UTC
app has been blocked,error log :
ERROR: Error message: app has been blocked.
ERROR: Can not get 'cid' from http://www.bilibili.com/video/av4057188/

**Comment by persmule** [comment] 2016-03-10 12:31
When using GET at http(s)://api.bilibili.com/view?id=3227664&sign=103c7f198a1a8a44b04e172a83d43640&appkey=85eb6835b0a1034e&page=1&type=json
returns {"code":-1,"error":"app has been blocked."}.
It seems that Twistencent starts to do something bad.

**Comment by m13253** [comment] 2016-03-10 15:04
I confirmed this problem.

@cnbeining , can you help me solve the problem?

**Comment by striges** [comment] 2016-03-11 02:49
new android appkey is c1b107428d337928. However, I cannot get "sign" field correctly hashed:
b'{"code":-3,"message":"API sign invalid","ts":1457664215}'

bilibili-helper's appkey is valid and can be used without "sign". But just don't want to abuse it.

**Comment by cnbeining** [comment] 2016-03-11 03:38
I am working with them. @m13253

**Comment by cnbeining** [comment] 2016-03-11 04:42
I am thinking from now on we cannot release the ```secretkey``` in our programme.

**Comment by m13253** [comment] 2016-03-11 04:45
> I am thinking from now on we cannot release the secretkey in our programme.

Can we use a server to do the request? (But too many requests from the same IP might cause an IP ban?)
Have you tried to contact the Bilibili official?

**Comment by cnbeining** [comment] 2016-03-11 04:54
Yes I am working directly with them and found out that I am in an awkward position.

Here's the problem: since I am working with multiple similar projects, I would like an universal way of dealing such problem.

For ```you-get```, I simply cannot rely on any external service to finish my job. For ```Biligrab```, I do not want to do that, either.

It is wrong to have some backdoor opened from their side. 

But it is clear that it is just impossible to hide something in your software. Especially open-source ones.

Also, for the sake of being nice, I do not want to use anyone else's key.

What am I supposed to do?

**Comment by cnbeining** [comment] 2016-03-11 05:16
Maybe...check the latest ```Biligrab```?

**Comment by m13253** [comment] 2016-03-11 05:23
It is said that a certain Bilibili player for Mac has cracked out the key of the Android client.

![img_20160311_131954](https://cloud.githubusercontent.com/assets/1808930/13694056/5c1ce050-e78c-11e5-988c-f2b5e03fa9aa.jpg)

**Comment by cnbeining** [comment] 2016-03-11 05:25
That is an outdated key, said ****.

I just do not like that approach.

**Comment by persmule** [comment] 2016-03-11 13:42
Why not? We do not need to honor such a corrupted company like Twistencent.

**Comment by persmule** [comment] 2016-03-11 13:52
Or you may add an interface to allow users to use their own appkey, and even with a default path...

**Comment by wnereiz** [comment] 2016-03-11 13:55
It's meaningful that continue maintaining this project without regarding the appkey. People can get keys by themselves by regular ways if they want.
So, don't stop the project.

**Comment by cnbeining** [comment] 2016-03-11 17:11
My approach for now: [Here](https://github.com/cnbeining/Biligrab/commit/55ecddd896a60abc1881e3dfa706b056122f26ba)

Also refer to: [Soimort's thought](https://github.com/soimort/you-get/commit/0ac3bdd5b3139976502a79ef2cf684c92420e9cb#commitcomment-16636950)

@m13253 

@persmule I am thinking about the same thing.

@wnereiz No we are not going to just abandon our project.

**Comment by cnbeining** [comment] 2016-03-11 17:27
See #51 .

**Comment by m13253** [comment] 2016-03-12 07:44
Fixed in #51

**Closed by m13253** 2016-03-12 07:44 UTC
